<?php
$this->headLink()->prependStylesheet('/css/style.css');
$this->inlineScript()->prependFile('/scripts/script.js');
?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <link rel="shortcut icon" href="/favicon.ico" />
        <title><?php echo $this->headTitle('mezzio')->setSeparator(' - ')->setAutoEscape(false)?></title>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headLink(); ?>
    </head>
    <body class="app">
        <div id="header">
            <div>This is where the navigation would be...</div>
        </div>

        <div id="main">
            <?php echo $this->content; ?>
        </div>

        <div id="footer">
            <p>Robert worked on this in 2021.</p>
        </div>

        <?php echo $this->inlineScript(); ?>
    </body>
</html>
