<?php
$this->headLink()->prependStylesheet('/css/style.css');
$this->inlineScript()->prependFile('/scripts/script.js');
$pageTitle = $this->headTitle()->offsetGet(0);
?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <link rel="shortcut icon" href="/favicon.ico" />
        <title><?php echo $pageTitle; ?> - A code jump start with Laminas Mezzio</title>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headLink(); ?>
    </head>
    <body>
        <div id="page">
            <div id="header">
                <h1><?php echo $pageTitle; ?></h1>
            </div>

            <div id="main">
                <?php echo $this->content; ?>
            </div>

            <div id="footer">
                <p>Robert worked on this in 2021.</p>
            </div>

        </div>
        <?php echo $this->inlineScript(); ?>
    </body>
</html>
