<?php $this->headTitle('Demo page'); ?>

<p>
    This project should lets me get new projects started a little faster. The nice thing about Laminas is that it lets you use what ever you want. Unfortunatly, gathering the components you want and configuring them, can take up a bit of your time. But you end up with a project that fits your exact needs.
</p>
<p>
    The base of this project is Laminas Mezzio with Doctrine2, Monolog, Whoops and the Laminas ViewRenderer.
    Doctrine2 is one of my favorite components, including this component in this project will save me a lot of time in the future.
    Templating systems often to too many things, but not always in a way you would like. The Laminas ViewRenderer is basically a PhpRenderer, so this will benefit Php programmers.
</p>
<p>
    Feel free to use this project as you like, let me know what component you think should be added to this primer.
</p>
